#!/bin/bash

TARBALLURL=$(curl -s https://api.github.com/repos/interactive-decisions-chain/idc-core/releases/latest | grep browser_download_url | grep -e "idc_node.*linux64" | cut -d '"' -f 4)
TARBALLNAME=$(curl -s https://api.github.com/repos/interactive-decisions-chain/idc-core/releases/latest | grep browser_download_url | grep -e "idc_node.*linux64" | cut -d '"' -f 4 | cut -d "/" -f 9)
IDCVERSION=$(curl -s https://api.github.com/repos/interactive-decisions-chain/idc-core/releases/latest | grep browser_download_url | grep -e "idc_node.*linux64" | cut -d '"' -f 4 | cut -d "/" -f 8)

LOCALVERSION=$(idchain-cli --version | cut -d " " -f 6)
REMOTEVERSION=$(curl -s https://api.github.com/repos/interactive-decisions-chain/idc-core/releases/latest | jq -r ".tag_name")

if [[ "$LOCALVERSION" = "$REMOTEVERSION" ]]; then
  echo "No update necessary."
  exit 0
fi

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root."
  exit 1
fi

USER=$(ps -o user= -p "$(pgrep idchaind)")
USERHOME=$(eval echo "~$USER")

echo "Downloading new version..."
wget "$TARBALLURL"

echo "Shutting down masternode..."
if [ -e /etc/systemd/system/idchaind.service ]; then
  systemctl stop idchaind
else
  su -c "idchain-cli stop" "$USER"
fi

echo "Installing Bulwark $IDCVERSION..."
rm /usr/local/bin/idchaind /usr/local/bin/idchain-cli
tar -xzvf "$TARBALLNAME" -C /usr/local/bin
rm "$TARBALLNAME"

if [ -e /usr/bin/idchaind ];then rm -rf /usr/bin/idchaind; fi
if [ -e /usr/bin/idchain-cli ];then rm -rf /usr/bin/idchain-cli; fi
if [ -e /usr/bin/idchain-tx ];then rm -rf /usr/bin/idchain-tx; fi

# Remove addnodes from idchain.conf
sed -i '/^addnode/d' "$USERHOME/.idchain/idchain.conf"

# Add Fail2Ban memory hack if needed
if ! grep -q "ulimit -s 256" /etc/default/fail2ban; then
  echo "ulimit -s 256" | sudo tee -a /etc/default/fail2ban
  systemctl restart fail2ban
fi

echo "Restarting Bulwark daemon..."
if [ -e /etc/systemd/system/idchaind.service ]; then
  systemctl disable idchaind
  rm /etc/systemd/system/idchaind.service
fi

cat > /etc/systemd/system/idchaind.service << EOL
[Unit]
Description=Bulwarks's distributed currency daemon
After=network-online.target
[Service]
Type=forking
User=${USER}
WorkingDirectory=${USERHOME}
ExecStart=/usr/local/bin/idchaind -conf=${USERHOME}/.idchain/idchain.conf -datadir=${USERHOME}/.idchain
ExecStop=/usr/local/bin/idchain-cli -conf=${USERHOME}/.idchain/idchain.conf -datadir=${USERHOME}/.idchain stop
Restart=on-failure
RestartSec=1m
StartLimitIntervalSec=5m
StartLimitInterval=5m
StartLimitBurst=3
[Install]
WantedBy=multi-user.target
EOL
sudo systemctl enable idchaind
sudo systemctl start idchaind

rm -f /usr/local/bin/mn_upodater
curl -o /usr/local/bin/idchainupdate https://raw.githubusercontent.com/interactive-decisions-chain/IDC-MN-Autodeploy/master/mn_updater
chmod a+x /usr/local/bin/mn_updater

if ! systemctl status idchaind | grep -q "active (running)"; then
  echo "ERROR: Failed to start idchaind. Please contact support."
  exit
fi

echo "Masternode is syncing. Masternode update completed."
